name: Source Workflow

on:
  push:
    branches:
      - source

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set Variable
        id: set_variable
        run: echo "::set-output name=myVariable::MyVariableValue"

      - name: Store Variable
        run: |
          echo ${{ steps.set_variable.outputs.myVariable }} > variable.txt
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add variable.txt
          git commit -m "Store variable"
          git push
